module.exports = {
  idAboutFeatureAddItem: "feature-additem",
  idAboutFeatureStatus: "feature-status",
  idAboutFeatureTx: "feature-tx",
  idFeatureBarcodelabel: "feature-barcodelabel",
  idFeatureLocation: "feature-location",
  idFeatureLowstock: "feature-lowstock",
  idFeatureSummary: "feature-summary",
  idFeatureViewPastQuantity: "feature-view-past-quantity",
  urlConsulting: "https://whattime.co.kr/boxhero/demo",
  urlDownloadApp: "https://redirect.appmetrica.yandex.com/serve/530934382265923250",
  urlDownloadAppDable: "https://redirect.appmetrica.yandex.com/serve/675474761484095974",
  urlDownloadAppKakao: "https://redirect.appmetrica.yandex.com/serve/99014008425711055",
  urlDownloadAppSearchAd: "https://redirect.appmetrica.yandex.com/serve/243082618806020699",
  urlDownloadOsx: "https://boxhero-autoupdate.s3.ap-northeast-2.amazonaws.com/BoxHero-latest.dmg",
  urlDownloadWindows: "https://boxhero-autoupdate.s3.ap-northeast-2.amazonaws.com/BoxHero-latest.exe",
  urlFaqPaymentDomestic: "https://docs-ko.boxhero-app.com/docs/pricing#%EA%B5%AD%EB%82%B4-%EC%B9%B4%EB%93%9C-%EB%B0%8F-%EA%B3%84%EC%A2%8C%EC%9D%B4%EC%B2%B4-%EA%B2%B0%EC%A0%9C-%EB%B0%A9%EB%B2%95",
  urlKakaoTalk: "http://pf.kakao.com/_rHxgpxl/chat",
  urlStart: "https://web.boxhero-app.com/team",
  urlWhatsApp: "https://api.whatsapp.com/send?phone=827086704320",
};
